version: "3.9"

services:
  api:
    build: ./PortfolioApi
    container_name: portfolio_api
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot:/etc/letsencrypt
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./html:/var/www/html
    entrypoint: >
      sh -c "trap exit TERM; while :; do
             certbot renew --webroot -w /var/www/html;
             sleep 12h;
             done"